  dir:
    status: false
    path: "/"

  provider:
    status: true
    val: animixplay

  quality:
    status: true
    val: 1080/best

  range:
    status: false
    val: 1-89

  special:
    status: false
    val: latest-89
