---
name: "release"

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: "Release"
    runs-on: "windows-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          pip install pyinstaller
          cd $GITHUB_WORKSPACE
          pyinstaller --onefile --icon .\logo.ico .\main.py
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Automatic Build"
          files: |
            LICENSE.txt
            *.exe
